// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// Custom exception for Customer notfound operations

using System;
using System.Collections.Generic;
using Binah.Core.Exceptions;

namespace Acme.SupplyChain.Generated.Exceptions
{
    /// <summary>
    /// Exception thrown when Customer notfound operation fails
    /// Entity: A customer entity
    /// </summary>
    public class CustomerNotFoundException : BinahException
    {
        /// <summary>
        /// The type of entity that caused the exception
        /// </summary>
        public string EntityType { get; }

        /// <summary>
        /// Optional properties related to the failed operation
        /// </summary>
        public Dictionary<string, object>? Properties { get; }

        /// <summary>
        /// Initializes a new instance of CustomerNotFoundException
        /// </summary>
        /// <param name="message">The error message</param>
        public CustomerNotFoundException(string message)
            : base($"Could not find Customer: {message}", "CUSTOMER_NOT_FOUND_FAILED")
        {
            EntityType = "Customer";
        }

        /// <summary>
        /// Initializes a new instance of CustomerNotFoundException with an inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="innerException">The inner exception</param>
        public CustomerNotFoundException(string message, Exception innerException)
            : base($"Could not find Customer: {message}", "CUSTOMER_NOT_FOUND_FAILED", innerException)
        {
            EntityType = "Customer";
        }

        /// <summary>
        /// Initializes a new instance of CustomerNotFoundException with additional properties
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        public CustomerNotFoundException(string message, Dictionary<string, object> properties)
            : base($"Could not find Customer: {message}", "CUSTOMER_NOT_FOUND_FAILED")
        {
            EntityType = "Customer";
            Properties = properties;
        }

        /// <summary>
        /// Initializes a new instance of CustomerNotFoundException with properties and inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        /// <param name="innerException">The inner exception</param>
        public CustomerNotFoundException(string message, Dictionary<string, object> properties, Exception innerException)
            : base($"Could not find Customer: {message}", "CUSTOMER_NOT_FOUND_FAILED", innerException)
        {
            EntityType = "Customer";
            Properties = properties;
        }
    }
}
