// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// Custom exception for Order notfound operations

using System;
using System.Collections.Generic;
using Binah.Core.Exceptions;

namespace Acme.SupplyChain.Generated.Exceptions
{
    /// <summary>
    /// Exception thrown when Order notfound operation fails
    /// Entity: A customer purchase order
    /// </summary>
    public class OrderNotFoundException : BinahException
    {
        /// <summary>
        /// The type of entity that caused the exception
        /// </summary>
        public string EntityType { get; }

        /// <summary>
        /// Optional properties related to the failed operation
        /// </summary>
        public Dictionary<string, object>? Properties { get; }

        /// <summary>
        /// Initializes a new instance of OrderNotFoundException
        /// </summary>
        /// <param name="message">The error message</param>
        public OrderNotFoundException(string message)
            : base($"Could not find Order: {message}", "ORDER_NOT_FOUND_FAILED")
        {
            EntityType = "Order";
        }

        /// <summary>
        /// Initializes a new instance of OrderNotFoundException with an inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="innerException">The inner exception</param>
        public OrderNotFoundException(string message, Exception innerException)
            : base($"Could not find Order: {message}", "ORDER_NOT_FOUND_FAILED", innerException)
        {
            EntityType = "Order";
        }

        /// <summary>
        /// Initializes a new instance of OrderNotFoundException with additional properties
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        public OrderNotFoundException(string message, Dictionary<string, object> properties)
            : base($"Could not find Order: {message}", "ORDER_NOT_FOUND_FAILED")
        {
            EntityType = "Order";
            Properties = properties;
        }

        /// <summary>
        /// Initializes a new instance of OrderNotFoundException with properties and inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        /// <param name="innerException">The inner exception</param>
        public OrderNotFoundException(string message, Dictionary<string, object> properties, Exception innerException)
            : base($"Could not find Order: {message}", "ORDER_NOT_FOUND_FAILED", innerException)
        {
            EntityType = "Order";
            Properties = properties;
        }
    }
}
