// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// Custom exception for Order creation operations

using System;
using System.Collections.Generic;
using Binah.Core.Exceptions;

namespace Acme.SupplyChain.Generated.Exceptions
{
    /// <summary>
    /// Exception thrown when Order creation operation fails
    /// Entity: A customer purchase order
    /// </summary>
    public class OrderCreationException : BinahException
    {
        /// <summary>
        /// The type of entity that caused the exception
        /// </summary>
        public string EntityType { get; }

        /// <summary>
        /// Optional properties related to the failed operation
        /// </summary>
        public Dictionary<string, object>? Properties { get; }

        /// <summary>
        /// Initializes a new instance of OrderCreationException
        /// </summary>
        /// <param name="message">The error message</param>
        public OrderCreationException(string message)
            : base($"Failed to create Order: {message}", "ORDER_CREATE_FAILED")
        {
            EntityType = "Order";
        }

        /// <summary>
        /// Initializes a new instance of OrderCreationException with an inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="innerException">The inner exception</param>
        public OrderCreationException(string message, Exception innerException)
            : base($"Failed to create Order: {message}", "ORDER_CREATE_FAILED", innerException)
        {
            EntityType = "Order";
        }

        /// <summary>
        /// Initializes a new instance of OrderCreationException with additional properties
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        public OrderCreationException(string message, Dictionary<string, object> properties)
            : base($"Failed to create Order: {message}", "ORDER_CREATE_FAILED")
        {
            EntityType = "Order";
            Properties = properties;
        }

        /// <summary>
        /// Initializes a new instance of OrderCreationException with properties and inner exception
        /// </summary>
        /// <param name="message">The error message</param>
        /// <param name="properties">Additional properties related to the error</param>
        /// <param name="innerException">The inner exception</param>
        public OrderCreationException(string message, Dictionary<string, object> properties, Exception innerException)
            : base($"Failed to create Order: {message}", "ORDER_CREATE_FAILED", innerException)
        {
            EntityType = "Order";
            Properties = properties;
        }
    }
}
