// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acme.SupplyChain.Entities
{
    /// <summary>
    /// A customer entity
    /// </summary>
    [Table("customer")]
    public class Customer : IEntity
    {
        /// <summary>Unique customer identifier</summary>
        [Key]
        [Required]
        public Guid CustomerId { get; set; }

        /// <summary>Company name</summary>
        [Required]
        [StringLength(200, MinimumLength = 2)]
        public string CompanyName { get; set; }

        /// <summary>Primary email address</summary>
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")]
        public string Email { get; set; }

        /// <summary>Primary phone number</summary>
        public string Phone { get; set; }

        /// <summary>Primary address</summary>
        [Required]
        public string Address { get; set; }

        /// <summary>Created timestamp</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Last updated timestamp</summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Soft delete flag</summary>
        public bool IsDeleted { get; set; }
    }
}
