// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acme.SupplyChain.Entities
{
    /// <summary>
    /// A customer purchase order
    /// </summary>
    [Table("order")]
    public class Order : IEntity
    {
        /// <summary>Unique order identifier</summary>
        [Key]
        [Required]
        public Guid OrderId { get; set; }

        /// <summary>Human-readable order number</summary>
        [Required]
        [RegularExpression(@"^ORD-\d{8}$")]
        public string OrderNumber { get; set; }

        /// <summary>Reference to customer</summary>
        [Required]
        public Guid CustomerId { get; set; }

        /// <summary>Total order amount</summary>
        [Required]
        [Range(0, 999999999.99)]
        public decimal TotalAmount { get; set; }

        /// <summary>Order status</summary>
        [Required]
        public string Status { get; set; }

        /// <summary>When the order was placed</summary>
        [Required]
        public DateTime OrderDate { get; set; }

        /// <summary>Created timestamp</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Last updated timestamp</summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Soft delete flag</summary>
        public bool IsDeleted { get; set; }
    }
}
