// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Acme.SupplyChain.Entities
{
    /// <summary>
    /// A product in the catalog
    /// </summary>
    [Table("product")]
    public class Product : IEntity
    {
        [Key]
        [Required]
        public Guid ProductId { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]{3}-\d{6}$")]
        public string SKU { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 3)]
        public string Name { get; set; }

        public string Description { get; set; }

        [Required]
        [Range(0, 1.7976931348623157E+308)]
        public decimal UnitPrice { get; set; }

        [Required]
        [Range(0, 1.7976931348623157E+308)]
        public int StockQuantity { get; set; }

        /// <summary>Created timestamp</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Last updated timestamp</summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Soft delete flag</summary>
        public bool IsDeleted { get; set; }
    }
}
