// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System.Collections.Generic;
using Acme.SupplyChain.Entities;

namespace Acme.SupplyChain.Repositories.Models
{
    /// <summary>
    /// Order entity with its relationships
    /// </summary>
    public class OrderWithRelationships
    {
        /// <summary>The Order entity</summary>
        public required Order Entity { get; set; }

        /// <summary>Related entities grouped by relationship type</summary>
        public Dictionary<string, List<object>> RelatedEntities { get; set; } = new();
    }
}
