// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;

namespace Acme.SupplyChain.DTOs
{
    /// <summary>
    /// DTO for creating a new Customer
    /// </summary>
    public record CreateCustomerDto
    {
        /// <summary>Company name</summary>
        [Required]
        [StringLength(200, MinimumLength = 2)]
        public required string CompanyName { get; init; }
        /// <summary>Primary email address</summary>
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")]
        public required string Email { get; init; }
        /// <summary>Primary phone number</summary>
        public string Phone { get; init; }
        /// <summary>Primary address</summary>
        [Required]
        public required string Address { get; init; }
    }
}
