// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;

namespace Acme.SupplyChain.DTOs
{
    /// <summary>
    /// DTO for creating a new Product
    /// </summary>
    public record CreateProductDto
    {
        [Required]
        [RegularExpression(@"^[A-Z]{3}-\d{6}$")]
        public required string SKU { get; init; }
        [Required]
        [StringLength(200, MinimumLength = 3)]
        public required string Name { get; init; }
        public string Description { get; init; }
        [Required]
        [Range(0, double.MaxValue)]
        public required decimal UnitPrice { get; init; }
        [Required]
        [Range(0, double.MaxValue)]
        public required int StockQuantity { get; init; }
    }
}
