// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;

namespace Acme.SupplyChain.DTOs
{
    /// <summary>
    /// DTO for creating a new Order
    /// </summary>
    public record CreateOrderDto
    {
        /// <summary>Human-readable order number</summary>
        [Required]
        [RegularExpression(@"^ORD-\d{8}$")]
        public required string OrderNumber { get; init; }
        /// <summary>Reference to customer</summary>
        [Required]
        public required Guid CustomerId { get; init; }
        /// <summary>Total order amount</summary>
        [Required]
        [Range(0, 999999999.99)]
        public required decimal TotalAmount { get; init; }
        /// <summary>Order status</summary>
        [Required]
        public required string Status { get; init; }
        /// <summary>When the order was placed</summary>
        [Required]
        public required DateTime OrderDate { get; init; }
    }
}
