// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;

namespace Acme.SupplyChain.DTOs
{
    /// <summary>
    /// A product in the catalog
    /// </summary>
    public record ProductDto
    {
        public required Guid ProductId { get; init; }
        public required string SKU { get; init; }
        public required string Name { get; init; }
        public string Description { get; init; }
        public required decimal UnitPrice { get; init; }
        public required int StockQuantity { get; init; }
    }
}
