// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.ComponentModel.DataAnnotations;

namespace Acme.SupplyChain.DTOs
{
    /// <summary>
    /// DTO for updating an existing Product
    /// </summary>
    public record UpdateProductDto
    {
        [Required]
        [RegularExpression(@"^[A-Z]{3}-\d{6}$")]
        public string SKU { get; init; }
        [Required]
        [StringLength(200, MinimumLength = 3)]
        public string Name { get; init; }
        public string Description { get; init; }
        [Required]
        [Range(0, double.MaxValue)]
        public decimal? UnitPrice { get; init; }
        [Required]
        [Range(0, double.MaxValue)]
        public int? StockQuantity { get; init; }
    }
}
