// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// FluentValidation validator for Update DTO

using FluentValidation;
using System;

namespace Acme.SupplyChain.Generated.Validators
{
    /// <summary>
    /// Validator for UpdateProductDto
    /// </summary>
    public class UpdateProductValidator : AbstractValidator<UpdateProductDto>
    {
        public UpdateProductValidator()
        {

            // Validation rules for SKU (when provided)
            When(x => x.SKU != null, () =>
            {
                RuleFor(x => x.SKU)
                    .NotEmpty()
                    .Matches(@"^[A-Z]{3}-\d{6}$");
            });

            // Validation rules for Name (when provided)
            When(x => x.Name != null, () =>
            {
                RuleFor(x => x.Name)
                    .NotEmpty()
                    .Length(3, 200);
            });

            // Validation rules for UnitPrice (when provided)
            When(x => x.UnitPrice != null, () =>
            {
                RuleFor(x => x.UnitPrice)
                    .NotEmpty()
                    .GreaterThanOrEqualTo(0m);
            });

            // Validation rules for StockQuantity (when provided)
            When(x => x.StockQuantity != null, () =>
            {
                RuleFor(x => x.StockQuantity)
                    .NotEmpty()
                    .GreaterThanOrEqualTo(0m);
            });
        }
    }
}
