// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// FluentValidation validator for Update DTO

using FluentValidation;
using System;

namespace Acme.SupplyChain.Generated.Validators
{
    /// <summary>
    /// Validator for UpdateCustomerDto
    /// </summary>
    public class UpdateCustomerValidator : AbstractValidator<UpdateCustomerDto>
    {
        public UpdateCustomerValidator()
        {

            // Validation rules for CompanyName (when provided)
            When(x => x.CompanyName != null, () =>
            {
                RuleFor(x => x.CompanyName)
                    .NotEmpty().WithMessage("Company name is required")
                    .Length(2, 200);
            });

            // Validation rules for Email (when provided)
            When(x => x.Email != null, () =>
            {
                RuleFor(x => x.Email)
                    .NotEmpty().WithMessage("Primary email address is required")
                    .Matches(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
                    .EmailAddress();
            });

            // Validation rules for Address (when provided)
            When(x => x.Address != null, () =>
            {
                RuleFor(x => x.Address)
                    .NotEmpty().WithMessage("Primary address is required");
            });
        }
    }
}
