// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0
// FluentValidation validator for Update DTO

using FluentValidation;
using System;

namespace Acme.SupplyChain.Generated.Validators
{
    /// <summary>
    /// Validator for UpdateOrderDto
    /// </summary>
    public class UpdateOrderValidator : AbstractValidator<UpdateOrderDto>
    {
        public UpdateOrderValidator()
        {

            // Validation rules for OrderNumber (when provided)
            When(x => x.OrderNumber != null, () =>
            {
                RuleFor(x => x.OrderNumber)
                    .NotEmpty().WithMessage("Human-readable order number is required")
                    .Matches(@"^ORD-\d{8}$");
            });

            // Validation rules for CustomerId (when provided)
            When(x => x.CustomerId != null, () =>
            {
                RuleFor(x => x.CustomerId)
                    .NotEmpty().WithMessage("Reference to customer is required");
            });

            // Validation rules for TotalAmount (when provided)
            When(x => x.TotalAmount != null, () =>
            {
                RuleFor(x => x.TotalAmount)
                    .NotEmpty().WithMessage("Total order amount is required")
                    .InclusiveBetween(0m, 999999999.99m);
            });

            // Validation rules for Status (when provided)
            When(x => x.Status != null, () =>
            {
                RuleFor(x => x.Status)
                    .NotEmpty().WithMessage("Order status is required")
                    .Must(x => new[] { "Pending", "Processing", "Shipped", "Delivered", "Cancelled" }.Contains(x))
                    .WithMessage("Value must be one of: Pending, Processing, Shipped, Delivered, Cancelled");
            });

            // Validation rules for OrderDate (when provided)
            When(x => x.OrderDate != null, () =>
            {
                RuleFor(x => x.OrderDate)
                    .NotEmpty().WithMessage("When the order was placed is required");
            });
        }
    }
}
