// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Acme.SupplyChain.Entities;
using Acme.SupplyChain.Repositories.Models;

namespace Acme.SupplyChain.Repositories.Interfaces
{
    /// <summary>
    /// Repository interface for Customer entity operations
    /// </summary>
    public interface ICustomerRepository
    {
        /// <summary>
        /// Creates a new Customer entity
        /// </summary>
        Task<Customer> CreateAsync(Customer entity, string tenantId);

        /// <summary>
        /// Retrieves a Customer by ID
        /// </summary>
        Task<Customer?> GetByIdAsync(Guid id, string tenantId);

        /// <summary>
        /// Retrieves all Customer entities with pagination
        /// </summary>
        Task<IEnumerable<Customer>> GetAllAsync(string tenantId, int skip = 0, int limit = 100);

        /// <summary>
        /// Updates an existing Customer entity
        /// </summary>
        Task<Customer> UpdateAsync(Customer entity, string tenantId);

        /// <summary>
        /// Deletes a Customer by ID
        /// </summary>
        Task DeleteAsync(Guid id, string tenantId);

        /// <summary>
        /// Retrieves a Customer with all its relationships
        /// </summary>
        Task<CustomerWithRelationships?> GetWithRelationshipsAsync(Guid id, string tenantId);
    }
}
