// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Acme.SupplyChain.Entities;
using Acme.SupplyChain.Repositories.Models;

namespace Acme.SupplyChain.Repositories.Interfaces
{
    /// <summary>
    /// Repository interface for Product entity operations
    /// </summary>
    public interface IProductRepository
    {
        /// <summary>
        /// Creates a new Product entity
        /// </summary>
        Task<Product> CreateAsync(Product entity, string tenantId);

        /// <summary>
        /// Retrieves a Product by ID
        /// </summary>
        Task<Product?> GetByIdAsync(Guid id, string tenantId);

        /// <summary>
        /// Retrieves all Product entities with pagination
        /// </summary>
        Task<IEnumerable<Product>> GetAllAsync(string tenantId, int skip = 0, int limit = 100);

        /// <summary>
        /// Updates an existing Product entity
        /// </summary>
        Task<Product> UpdateAsync(Product entity, string tenantId);

        /// <summary>
        /// Deletes a Product by ID
        /// </summary>
        Task DeleteAsync(Guid id, string tenantId);

        /// <summary>
        /// Retrieves a Product with all its relationships
        /// </summary>
        Task<ProductWithRelationships?> GetWithRelationshipsAsync(Guid id, string tenantId);
    }
}
