// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Acme.SupplyChain.DTOs;
using Acme.SupplyChain.Services;

namespace Acme.SupplyChain.Controllers
{
    /// <summary>
    /// API Controller for Order operations
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class OrderController : ControllerBase
    {
        private readonly IOrderService _service;
        private readonly ILogger<OrderController> _logger;

        public OrderController(IOrderService service, ILogger<OrderController> logger)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Get all Order entities
        /// </summary>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<OrderDto>), 200)]
        public async Task<ActionResult<IEnumerable<OrderDto>>> GetAll()
        {
            try
            {
                _logger.LogInformation("Retrieving all Order entities");
                var entities = await _service.GetAllAsync();
                return Ok(entities);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Order entities");
                return StatusCode(500, "An error occurred while retrieving entities");
            }
        }

        /// <summary>
        /// Get a specific Order by ID
        /// </summary>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(OrderDto), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<OrderDto>> GetById(Guid id)
        {
            try
            {
                _logger.LogInformation("Retrieving Order with ID: {Id}", id);
                var entity = await _service.GetByIdAsync(id);

                if (entity == null)
                {
                    _logger.LogWarning("Order with ID {Id} not found", id);
                    return NotFound();
                }

                return Ok(entity);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Order with ID: {Id}", id);
                return StatusCode(500, "An error occurred while retrieving the entity");
            }
        }

        /// <summary>
        /// Create a new Order
        /// </summary>
        [HttpPost]
        [ProducesResponseType(typeof(OrderDto), 201)]
        [ProducesResponseType(400)]
        public async Task<ActionResult<OrderDto>> Create([FromBody] CreateOrderDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                _logger.LogInformation("Creating new Order");
                var created = await _service.CreateAsync(dto);
                return CreatedAtAction(nameof(GetById), new { id = created.GetId() }, created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating Order");
                return StatusCode(500, "An error occurred while creating the entity");
            }
        }

        /// <summary>
        /// Update an existing Order
        /// </summary>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(OrderDto), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<OrderDto>> Update(Guid id, [FromBody] UpdateOrderDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                _logger.LogInformation("Updating Order with ID: {Id}", id);
                var updated = await _service.UpdateAsync(id, dto);

                if (updated == null)
                {
                    _logger.LogWarning("Order with ID {Id} not found", id);
                    return NotFound();
                }

                return Ok(updated);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Order with ID: {Id}", id);
                return StatusCode(500, "An error occurred while updating the entity");
            }
        }

        /// <summary>
        /// Delete a Order
        /// </summary>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                _logger.LogInformation("Deleting Order with ID: {Id}", id);
                var deleted = await _service.DeleteAsync(id);

                if (!deleted)
                {
                    _logger.LogWarning("Order with ID {Id} not found", id);
                    return NotFound();
                }

                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting Order with ID: {Id}", id);
                return StatusCode(500, "An error occurred while deleting the entity");
            }
        }
    }
}
