// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Acme.SupplyChain.DTOs;
using Acme.SupplyChain.Services;

namespace Acme.SupplyChain.Controllers
{
    /// <summary>
    /// API Controller for Product operations
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class ProductController : ControllerBase
    {
        private readonly IProductService _service;
        private readonly ILogger<ProductController> _logger;

        public ProductController(IProductService service, ILogger<ProductController> logger)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Get all Product entities
        /// </summary>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<ProductDto>), 200)]
        public async Task<ActionResult<IEnumerable<ProductDto>>> GetAll()
        {
            try
            {
                _logger.LogInformation("Retrieving all Product entities");
                var entities = await _service.GetAllAsync();
                return Ok(entities);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Product entities");
                return StatusCode(500, "An error occurred while retrieving entities");
            }
        }

        /// <summary>
        /// Get a specific Product by ID
        /// </summary>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(ProductDto), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<ProductDto>> GetById(Guid id)
        {
            try
            {
                _logger.LogInformation("Retrieving Product with ID: {Id}", id);
                var entity = await _service.GetByIdAsync(id);

                if (entity == null)
                {
                    _logger.LogWarning("Product with ID {Id} not found", id);
                    return NotFound();
                }

                return Ok(entity);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Product with ID: {Id}", id);
                return StatusCode(500, "An error occurred while retrieving the entity");
            }
        }

        /// <summary>
        /// Create a new Product
        /// </summary>
        [HttpPost]
        [ProducesResponseType(typeof(ProductDto), 201)]
        [ProducesResponseType(400)]
        public async Task<ActionResult<ProductDto>> Create([FromBody] CreateProductDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                _logger.LogInformation("Creating new Product");
                var created = await _service.CreateAsync(dto);
                return CreatedAtAction(nameof(GetById), new { id = created.GetId() }, created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating Product");
                return StatusCode(500, "An error occurred while creating the entity");
            }
        }

        /// <summary>
        /// Update an existing Product
        /// </summary>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(ProductDto), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<ProductDto>> Update(Guid id, [FromBody] UpdateProductDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                _logger.LogInformation("Updating Product with ID: {Id}", id);
                var updated = await _service.UpdateAsync(id, dto);

                if (updated == null)
                {
                    _logger.LogWarning("Product with ID {Id} not found", id);
                    return NotFound();
                }

                return Ok(updated);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Product with ID: {Id}", id);
                return StatusCode(500, "An error occurred while updating the entity");
            }
        }

        /// <summary>
        /// Delete a Product
        /// </summary>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                _logger.LogInformation("Deleting Product with ID: {Id}", id);
                var deleted = await _service.DeleteAsync(id);

                if (!deleted)
                {
                    _logger.LogWarning("Product with ID {Id} not found", id);
                    return NotFound();
                }

                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting Product with ID: {Id}", id);
                return StatusCode(500, "An error occurred while deleting the entity");
            }
        }
    }
}
