// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Neo4j.Driver;
using Acme.SupplyChain.Entities;
using Acme.SupplyChain.Repositories.Interfaces;
using Acme.SupplyChain.Repositories.Models;

namespace Acme.SupplyChain.Repositories.Implementations
{
    /// <summary>
    /// Neo4j repository implementation for Customer entity
    /// </summary>
    public class CustomerRepository : ICustomerRepository
    {
        private readonly IDriver _driver;
        private readonly ILogger<CustomerRepository> _logger;

        public CustomerRepository(IDriver driver, ILogger<CustomerRepository> logger)
        {
            _driver = driver ?? throw new ArgumentNullException(nameof(driver));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <inheritdoc/>
        public async Task<Customer> CreateAsync(Customer entity, string tenantId)
        {
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MERGE (e:Customer {
                    CustomerId: $customerId,
                    TenantId: $tenantId
                })
                SET e.CompanyName = $companyName,
                    e.Email = $email,
                    e.Phone = $phone,
                    e.Address = $address
                    ,
                    e.CreatedAt = datetime(),
                    e.UpdatedAt = datetime(),
                    e.IsDeleted = false
                RETURN e";

            await using var session = _driver.AsyncSession();
            try
            {
                var result = await session.ExecuteWriteAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new
                    {
                        customerId = entity.CustomerId,
                        tenantId = tenantId
                        , companyName = entity.CompanyName
                        , email = entity.Email
                        , phone = entity.Phone
                        , address = entity.Address
                    });
                    return await cursor.SingleAsync();
                });

                return MapToCustomer(result["e"].As<Neo4j.Driver.INode>());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating Customer in Neo4j");
                throw;
            }
        }

        /// <inheritdoc/>
        public async Task<Customer?> GetByIdAsync(Guid id, string tenantId)
        {
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MATCH (e:Customer {CustomerId: $id, TenantId: $tenantId, IsDeleted: false})
                RETURN e";

            await using var session = _driver.AsyncSession();
            try
            {
                var result = await session.ExecuteReadAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new { id, tenantId });
                    var records = await cursor.ToListAsync();
                    return records.Count > 0 ? records[0] : null;
                });

                if (result == null) return null;
                return MapToCustomer(result["e"].As<Neo4j.Driver.INode>());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Customer {Id} from Neo4j", id);
                throw;
            }
        }

        /// <inheritdoc/>
        public async Task<IEnumerable<Customer>> GetAllAsync(string tenantId, int skip = 0, int limit = 100)
        {
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MATCH (e:Customer {TenantId: $tenantId, IsDeleted: false})
                RETURN e
                ORDER BY e.CreatedAt DESC
                SKIP $skip
                LIMIT $limit";

            await using var session = _driver.AsyncSession();
            try
            {
                var results = await session.ExecuteReadAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new { tenantId, skip, limit });
                    return await cursor.ToListAsync();
                });

                return results.Select(record => MapToCustomer(record["e"].As<Neo4j.Driver.INode>())).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Customer entities from Neo4j");
                throw;
            }
        }

        /// <inheritdoc/>
        public async Task<Customer> UpdateAsync(Customer entity, string tenantId)
        {
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MATCH (e:Customer {CustomerId: $customerId, TenantId: $tenantId, IsDeleted: false})
                SET e.CompanyName = $companyName,
                    e.Email = $email,
                    e.Phone = $phone,
                    e.Address = $address,
                    e.UpdatedAt = datetime()
                RETURN e";

            await using var session = _driver.AsyncSession();
            try
            {
                var result = await session.ExecuteWriteAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new
                    {
                        customerId = entity.CustomerId,
                        tenantId = tenantId
                        , companyName = entity.CompanyName
                        , email = entity.Email
                        , phone = entity.Phone
                        , address = entity.Address
                    });
                    var records = await cursor.ToListAsync();
                    var record = records.Count > 0 ? records[0] : null;
                    if (record == null) throw new InvalidOperationException("Customer not found");
                    return record;
                });

                return MapToCustomer(result["e"].As<Neo4j.Driver.INode>());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Customer in Neo4j");
                throw;
            }
        }

        /// <inheritdoc/>
        public async Task DeleteAsync(Guid id, string tenantId)
        {
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MATCH (e:Customer {CustomerId: $id, TenantId: $tenantId})
                SET e.IsDeleted = true, e.UpdatedAt = datetime()
                RETURN e";

            await using var session = _driver.AsyncSession();
            try
            {
                await session.ExecuteWriteAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new { id, tenantId });
                    var records = await cursor.ToListAsync();
                    var result = records.FirstOrDefault();
                    if (result == null) throw new InvalidOperationException("Customer not found");
                    return result;
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting Customer {Id} from Neo4j", id);
                throw;
            }
        }

        /// <inheritdoc/>
        public async Task<CustomerWithRelationships?> GetWithRelationshipsAsync(Guid id, string tenantId)
        {
            if (string.IsNullOrWhiteSpace(tenantId)) throw new ArgumentException("Tenant ID cannot be null or empty", nameof(tenantId));

            const string cypher = @"
                MATCH (e:Customer {CustomerId: $id, TenantId: $tenantId, IsDeleted: false})
                OPTIONAL MATCH (e)-[r]->(related)
                WHERE related.TenantId = $tenantId AND related.IsDeleted = false
                RETURN e, collect({{type: type(r), node: related}}) AS relationships";

            await using var session = _driver.AsyncSession();
            try
            {
                var result = await session.ExecuteReadAsync(async tx =>
                {
                    var cursor = await tx.RunAsync(cypher, new { id, tenantId });
                    var records = await cursor.ToListAsync();
                    return records.Count > 0 ? records[0] : null;
                });

                if (result == null) return null;

                var withRelationships = new CustomerWithRelationships
                {
                    Entity = MapToCustomer(result["e"].As<Neo4j.Driver.INode>()),
                    RelatedEntities = new Dictionary<string, List<object>>()
                };

                var relationshipsData = result["relationships"].As<List<Dictionary<string, object>>>();
                foreach (var relData in relationshipsData)
                {
                    if (relData["node"] != null)
                    {
                        var relType = relData["type"].ToString();
                        var node = relData["node"] as Neo4j.Driver.INode;
                        if (node != null)
                        {
                            if (!withRelationships.RelatedEntities.ContainsKey(relType))
                            {
                                withRelationships.RelatedEntities[relType] = new List<object>();
                            }
                            withRelationships.RelatedEntities[relType].Add(node.Properties);
                        }
                    }
                }

                return withRelationships;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving Customer {Id} with relationships from Neo4j", id);
                throw;
            }
        }

        private Customer MapToCustomer(Neo4j.Driver.INode node)
        {
            return new Customer
            {
                CustomerId = node.Properties["CustomerId"].As<Guid>(),
                CompanyName = node.Properties.ContainsKey("CompanyName") ? node.Properties["CompanyName"].As<string>() : string.Empty,
                Email = node.Properties.ContainsKey("Email") ? node.Properties["Email"].As<string>() : string.Empty,
                Phone = node.Properties.ContainsKey("Phone") ? node.Properties["Phone"].As<string>() : string.Empty,
                Address = node.Properties.ContainsKey("Address") ? node.Properties["Address"].As<string>() : string.Empty,
                CreatedAt = node.Properties.ContainsKey("CreatedAt") ? node.Properties["CreatedAt"].As<DateTime>() : DateTime.UtcNow,
                UpdatedAt = node.Properties.ContainsKey("UpdatedAt") ? node.Properties["UpdatedAt"].As<DateTime>() : DateTime.UtcNow,
                IsDeleted = node.Properties.ContainsKey("IsDeleted") && node.Properties["IsDeleted"].As<bool>()
            };
        }
    }
}
