// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using AutoMapper;
using System;
using System.Collections.Generic;
using Acme.SupplyChain.DTOs;
using Acme.SupplyChain.Entities;
using Ontology.Regen.Generators.Mapper;

namespace Acme.SupplyChain.Generated.Mappings
{
    /// <summary>
    /// AutoMapper profile for Customer entity mappings
    /// </summary>
    public class CustomerMappingProfile : Profile
    {
        public CustomerMappingProfile()
        {
            // DTO to Entity mappings
            CreateMap<CustomerDto, Customer>();

            CreateMap<CreateCustomerDto, Customer>()
                .ForMember(dest => dest.CustomerId, opt => opt.Ignore()); // Generated by system

            CreateMap<UpdateCustomerDto, Customer>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Entity to DTO mappings
            CreateMap<Customer, CustomerDto>();

            // Entity to Neo4j Node mapping
            CreateMap<Customer, Neo4jNode>()
                .ForMember(dest => dest.Labels, opt => opt.MapFrom(src => new[] { "Customer" }))
                .ForMember(dest => dest.Properties, opt => opt.MapFrom(src => new Dictionary<string, object>
                {
                    ["CustomerId"] = src.CustomerId,
                    ["CompanyName"] = src.CompanyName,
                    ["Email"] = src.Email,
                    ["Phone"] = src.Phone,
                    ["Address"] = src.Address
                }));
        }
    }
}
