// <auto-generated />
// Generated from SupplyChainOntology vv1.0.0

using AutoMapper;
using System;
using System.Collections.Generic;
using Acme.SupplyChain.DTOs;
using Acme.SupplyChain.Entities;
using Ontology.Regen.Generators.Mapper;

namespace Acme.SupplyChain.Generated.Mappings
{
    /// <summary>
    /// AutoMapper profile for Order entity mappings
    /// </summary>
    public class OrderMappingProfile : Profile
    {
        public OrderMappingProfile()
        {
            // DTO to Entity mappings
            CreateMap<OrderDto, Order>();

            CreateMap<CreateOrderDto, Order>()
                .ForMember(dest => dest.OrderId, opt => opt.Ignore()); // Generated by system

            CreateMap<UpdateOrderDto, Order>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // Entity to DTO mappings
            CreateMap<Order, OrderDto>();

            // Entity to Neo4j Node mapping
            CreateMap<Order, Neo4jNode>()
                .ForMember(dest => dest.Labels, opt => opt.MapFrom(src => new[] { "Order" }))
                .ForMember(dest => dest.Properties, opt => opt.MapFrom(src => new Dictionary<string, object>
                {
                    ["OrderId"] = src.OrderId,
                    ["OrderNumber"] = src.OrderNumber,
                    ["CustomerId"] = src.CustomerId,
                    ["TotalAmount"] = src.TotalAmount,
                    ["Status"] = src.Status,
                    ["OrderDate"] = src.OrderDate
                }));
        }
    }
}
